// Ponto central de exportação dos submódulos do servidor (Server Architecture)
module.exports = {
  ...require("./core/titles"),
  ...require("./core/fs-atomic"),
  ...require("./core/security"),
  ...require("./core/device"),
  ...require("./core/desktop-ipc"),
  ...require("./core/log-buffer"),
  ...require("./core/paths"),
  ...require("./core/scan"),
  ...require("./core/tree-cache"),
  ...require("./libraries"),
  ...require("./progress"),
  ...require("./transcode/jobs"),
  ...require("./media"),
  ...require("./services/document-extractors"),
  ...require("./services/web-search"),
  ...require("./ai"),
  ...require("./subtitles"),
  ...require("./tutor"),
  ...require("./system"),
};
